/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectointermodular.prestamos;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Víctor Sánchez Llada, César Torre, Efrén Gutiérrez y Adrián Tresgallo.
 */
public class Prestamos extends javax.swing.JFrame {

    //Atributos
    private AccesoBaseDatos bd = AccesoBaseDatos.getInstance();

    /**
     * Creates new form PrestamosI
     */
    public Prestamos() {
        initComponents();
        //this.setLocationRelativeTo(null);
        //jPPortada.setVisible(true);
        mostrarImagen();
    }

    private void mostrarImagen() {

        //Imagen portada
        ImageIcon img = new ImageIcon(getClass().getClassLoader().getResource("Imagen/logo.jpg"));
        Icon icon = new ImageIcon(img.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), img.getIconWidth()));
        lblLogo.setIcon(icon);

        //Icono formulario
        Image icon2 = new ImageIcon(getClass().getClassLoader().getResource("Imagen/ico.png")).getImage();
        setIconImage(icon2);

        //Fondo JPanels
        ImageIcon fondo = new ImageIcon(getClass().getClassLoader().getResource("Imagen/fondo.jpg"));
        fondoJPanels(fondo, lblFondoSolicitar);
        fondoJPanels(fondo, lblFondoMostrar);
        fondoJPanels(fondo, lblFondoFirmar);

    }

    private void fondoJPanels(ImageIcon imageIcon, JLabel label) {
        Icon fondoSolicitar = new ImageIcon(imageIcon.getImage().getScaledInstance(label.getWidth(), label.getHeight(), imageIcon.getIconWidth()));
        label.setIcon(fondoSolicitar);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPortada = new javax.swing.JPanel();
        jBSolicitar = new javax.swing.JButton();
        jBCalcular = new javax.swing.JButton();
        jBMostrar = new javax.swing.JButton();
        jBBFirmar = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        jPSolicitar = new javax.swing.JPanel();
        jScrollPaneClientesSolicitar = new javax.swing.JScrollPane();
        jTableSolicitar = new javax.swing.JTable();
        jButtonVolverSolicitar = new javax.swing.JButton();
        jLabelDNISolicitar = new javax.swing.JLabel();
        jTextFieldDNISolicitar = new javax.swing.JTextField();
        jButtonBuscarSolicitar = new javax.swing.JButton();
        jButtonLimpiarSolicitar = new javax.swing.JButton();
        jLabelTituloSolicitar = new javax.swing.JLabel();
        jLabelDatosClienteSolicitar = new javax.swing.JLabel();
        jButtonProcesarSolicitar = new javax.swing.JButton();
        lblFondoSolicitar = new javax.swing.JLabel();
        jPCalcularPrestamo = new javax.swing.JPanel();
        jScrollPanePrestamo = new javax.swing.JScrollPane();
        jTableCalculo = new javax.swing.JTable();
        jLCalculoPrestamo = new javax.swing.JLabel();
        jBCalculo = new javax.swing.JButton();
        jBVolver = new javax.swing.JButton();
        jGrabar = new javax.swing.JButton();
        jPMostrar = new javax.swing.JPanel();
        jBVolverMostrar = new javax.swing.JButton();
        jLabelMostrar = new javax.swing.JLabel();
        jLabelFiltroMostrar = new javax.swing.JLabel();
        jComboBoxFiltroMostrar = new javax.swing.JComboBox<>();
        jTextFieldDatoMostrar = new javax.swing.JTextField();
        jButtonBuscarMostrar = new javax.swing.JButton();
        jButtonLimpiarMostrar = new javax.swing.JButton();
        jScrollPane1Mostrar = new javax.swing.JScrollPane();
        jTableMostrar = new javax.swing.JTable();
        lblFondoMostrar = new javax.swing.JLabel();
        jPFirmar = new javax.swing.JPanel();
        jLPrestamoConcedido = new javax.swing.JLabel();
        DNI = new javax.swing.JLabel();
        jTIntroDNI = new javax.swing.JTextField();
        jBPLimpiar = new javax.swing.JButton();
        jBFirmar = new javax.swing.JButton();
        jScrollPaneConcedidos = new javax.swing.JScrollPane();
        jBPreconcedidos2 = new javax.swing.JButton();
        jLFirmarPrestamo1 = new javax.swing.JLabel();
        jScrollPanePreconcedido = new javax.swing.JScrollPane();
        jLPrestamoPreconcedido1 = new javax.swing.JLabel();
        jBVolver1 = new javax.swing.JButton();
        lblFondoFirmar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Préstamos - Aurora Bank");
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPPortada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBSolicitar.setText("Solicitar");
        jBSolicitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSolicitarActionPerformed(evt);
            }
        });
        jPPortada.add(jBSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, -1, -1));

        jBCalcular.setText("Calcular");
        jBCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });
        jPPortada.add(jBCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, -1, -1));

        jBMostrar.setText("Mostrar");
        jBMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMostrarActionPerformed(evt);
            }
        });
        jPPortada.add(jBMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, -1, -1));

        jBBFirmar.setText("Firmar");
        jBBFirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBBFirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBFirmarActionPerformed(evt);
            }
        });
        jPPortada.add(jBBFirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, -1, -1));
        jPPortada.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 810, 580));
        lblLogo.getAccessibleContext().setAccessibleName("Logo");

        getContentPane().add(jPPortada, "card2");

        jPSolicitar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPaneClientesSolicitar.setViewportView(jTableSolicitar);

        jPSolicitar.add(jScrollPaneClientesSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 720, 190));

        jButtonVolverSolicitar.setText("Volver");
        jButtonVolverSolicitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVolverSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverSolicitarActionPerformed(evt);
            }
        });
        jPSolicitar.add(jButtonVolverSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, -1, -1));

        jLabelDNISolicitar.setText("DNI");
        jPSolicitar.add(jLabelDNISolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
        jPSolicitar.add(jTextFieldDNISolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 170, -1));

        jButtonBuscarSolicitar.setText("Buscar");
        jButtonBuscarSolicitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscarSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarSolicitarActionPerformed(evt);
            }
        });
        jPSolicitar.add(jButtonBuscarSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jButtonLimpiarSolicitar.setText("Limpiar");
        jButtonLimpiarSolicitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimpiarSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarSolicitarActionPerformed(evt);
            }
        });
        jPSolicitar.add(jButtonLimpiarSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jLabelTituloSolicitar.setText("Solicitar préstamo");
        jPSolicitar.add(jLabelTituloSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabelDatosClienteSolicitar.setText("Datos cliente:");
        jPSolicitar.add(jLabelDatosClienteSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jButtonProcesarSolicitar.setText("Solicitud de préstamo");
        jButtonProcesarSolicitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonProcesarSolicitar.setEnabled(false);
        jButtonProcesarSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcesarSolicitarActionPerformed(evt);
            }
        });
        jPSolicitar.add(jButtonProcesarSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, -1, -1));
        jPSolicitar.add(lblFondoSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 580));

        getContentPane().add(jPSolicitar, "card3");

        jPCalcularPrestamo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPanePrestamo.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPanePrestamo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jScrollPanePrestamoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jScrollPanePrestamo.setViewportView(jTableCalculo);

        jPCalcularPrestamo.add(jScrollPanePrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 620, 250));

        jLCalculoPrestamo.setText("Cálculo de Prestamos");
        jPCalcularPrestamo.add(jLCalculoPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 30));

        jBCalculo.setText("Calcular");
        jBCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalculoActionPerformed(evt);
            }
        });
        jPCalcularPrestamo.add(jBCalculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        jBVolver.setText("Volver");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });
        jPCalcularPrestamo.add(jBVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, -1, -1));

        jGrabar.setText("Grabar");
        jGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGrabarActionPerformed(evt);
            }
        });
        jPCalcularPrestamo.add(jGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        getContentPane().add(jPCalcularPrestamo, "card5");

        jPMostrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBVolverMostrar.setText("Volver");
        jBVolverMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBVolverMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverMostrarActionPerformed(evt);
            }
        });
        jPMostrar.add(jBVolverMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, -1, -1));

        jLabelMostrar.setText("Mostrar datos de clientes y préstamos");
        jPMostrar.add(jLabelMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelFiltroMostrar.setText("Filtro:");
        jPMostrar.add(jLabelFiltroMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jComboBoxFiltroMostrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Localidad" }));
        jComboBoxFiltroMostrar.setToolTipText("");
        jPMostrar.add(jComboBoxFiltroMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));
        jPMostrar.add(jTextFieldDatoMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 180, -1));

        jButtonBuscarMostrar.setText("Buscar");
        jButtonBuscarMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscarMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarMostrarActionPerformed(evt);
            }
        });
        jPMostrar.add(jButtonBuscarMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jButtonLimpiarMostrar.setText("Limpiar");
        jButtonLimpiarMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimpiarMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarMostrarActionPerformed(evt);
            }
        });
        jPMostrar.add(jButtonLimpiarMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        jTableMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1Mostrar.setViewportView(jTableMostrar);

        jPMostrar.add(jScrollPane1Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 690, 300));
        jPMostrar.add(lblFondoMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 580));

        getContentPane().add(jPMostrar, "card4");

        jPFirmar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLPrestamoConcedido.setText("Préstamos Concedidos");
        jPFirmar.add(jLPrestamoConcedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        DNI.setText("DNI");
        jPFirmar.add(DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jTIntroDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIntroDNIActionPerformed(evt);
            }
        });
        jPFirmar.add(jTIntroDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 150, -1));

        jBPLimpiar.setText("Limpiar");
        jBPLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBPLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPLimpiarActionPerformed(evt);
            }
        });
        jPFirmar.add(jBPLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jBFirmar.setText("Firmar");
        jBFirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBFirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFirmarActionPerformed(evt);
            }
        });
        jPFirmar.add(jBFirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, -1, -1));

        jScrollPaneConcedidos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jScrollPaneConcedidosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPFirmar.add(jScrollPaneConcedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 690, 170));

        jBPreconcedidos2.setText("Mostrar ");
        jBPreconcedidos2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBPreconcedidos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPreconcedidos2ActionPerformed(evt);
            }
        });
        jPFirmar.add(jBPreconcedidos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLFirmarPrestamo1.setText("Firmar Préstamo");
        jPFirmar.add(jLFirmarPrestamo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));
        jPFirmar.add(jScrollPanePreconcedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 570, 150));

        jLPrestamoPreconcedido1.setText("Préstamos Preconcedidos");
        jPFirmar.add(jLPrestamoPreconcedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jBVolver1.setText("Volver");
        jBVolver1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolver1ActionPerformed(evt);
            }
        });
        jPFirmar.add(jBVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, -1, -1));
        jPFirmar.add(lblFondoFirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 580));

        getContentPane().add(jPFirmar, "card6");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSolicitarActionPerformed
        // TODO add your handling code here:
        jPPortada.setVisible(false);
        jPSolicitar.setVisible(true);

        //Pruebas
        /*
        List<Cliente> clientes = MetodosBD.listarClientes();
        for (Cliente cliente : clientes) {
            System.out.println(cliente.toString());
        }
         */
    }//GEN-LAST:event_jBSolicitarActionPerformed

    private void jButtonVolverSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverSolicitarActionPerformed
        // TODO add your handling code here:
        jPSolicitar.setVisible(false);
        jPPortada.setVisible(true);
        jButtonLimpiarSolicitarActionPerformed(evt);

    }//GEN-LAST:event_jButtonVolverSolicitarActionPerformed

    private void jButtonLimpiarSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarSolicitarActionPerformed
        // TODO add your handling code here:
        jTextFieldDNISolicitar.setText("");
        jTableSolicitar.setModel(new DefaultTableModel());
        jButtonProcesarSolicitar.setEnabled(false);
    }//GEN-LAST:event_jButtonLimpiarSolicitarActionPerformed

    private void jBVolverMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverMostrarActionPerformed
        // TODO add your handling code here:
        jPMostrar.setVisible(false);
        jPPortada.setVisible(true);
        jButtonLimpiarMostrarActionPerformed(evt);
    }//GEN-LAST:event_jBVolverMostrarActionPerformed

    private void jBMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMostrarActionPerformed
        // TODO add your handling code here:
        jPPortada.setVisible(false);
        jPMostrar.setVisible(true);
    }//GEN-LAST:event_jBMostrarActionPerformed

    private void jButtonLimpiarMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarMostrarActionPerformed
        // TODO add your handling code here:
        jTextFieldDatoMostrar.setText("");
    }//GEN-LAST:event_jButtonLimpiarMostrarActionPerformed


    private void jButtonBuscarSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarSolicitarActionPerformed
        // TODO add your handling code here:

        /*
        DNI 98765432M casado con cliente y movimientos
        87654321V con morosidad
        54321098G no requisitos minimos
         */
        jTextFieldDNISolicitar.setText("98765432M");
        String dni = jTextFieldDNISolicitar.getText();

        if (Funciones.esCadenaValida(dni, "[0-9]{7,8}[A-Z a-z]")) {

            Cliente cliente = MetodosBD.clientePorDni(dni);

            if (cliente != null) {

                jButtonProcesarSolicitar.setEnabled(true);
                System.out.println(cliente.toString());

                String[] columnasTablaSolicitar = {"DNI", "Nombre", "Apellidos", "IBAN", "Tipo cuenta"};
                String[] datosCliente = {cliente.getDni(), cliente.getNombre(), cliente.getApellidos(), cliente.getCuentaBancaria().getIBAN(), cliente.getCuentaBancaria().getTipoCuenta().name()};
                DefaultTableModel modeloTabla = new DefaultTableModel(null, columnasTablaSolicitar);
                jTableSolicitar.setModel(modeloTabla);
                modeloTabla.addRow(datosCliente);

            } else {
                JOptionPane.showMessageDialog(null, "No existe como cliente del banco.", "Informativo", JOptionPane.INFORMATION_MESSAGE, null);
            }

        } else {
            JOptionPane.showMessageDialog(null, "El DNI no tiene el formato correcto.", "Informativo", JOptionPane.INFORMATION_MESSAGE, null);
            jButtonLimpiarSolicitarActionPerformed(evt);
        }

    }//GEN-LAST:event_jButtonBuscarSolicitarActionPerformed
/**
 * 
 * @param evt 
 */
    private void jBCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalculoActionPerformed
        // TODO add your handling code here:
        List<PrestamoPreconcedido>lista=MetodosBD.listarPrestamosPreconcedidos();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        if(!lista.isEmpty()){
        String[] columnasTablaSolicitar = {"NºPrestamo", "ID Cliente", "Fecha_Oferta","Cantidad","Periodo en Meses","Interés","Plazo de Aceptación"};
        DefaultTableModel modeloTabla = new DefaultTableModel(null, columnasTablaSolicitar);
        jTableCalculo.setModel(modeloTabla);

        for (PrestamoPreconcedido preconcedido : lista) {
            String[] datosPreconcedidos = {String.valueOf(preconcedido.getId()),preconcedido.getCliente().getUuid(),preconcedido.getFecha().format(formatter),
                String.valueOf(preconcedido.getCantidad()),String.valueOf(preconcedido.getPeriodoMeses()),String.valueOf(preconcedido.getPeriodoMeses()),
                String.valueOf(preconcedido.getPeriodoMeses())};   
            modeloTabla.addRow(datosPreconcedidos);
            }
        }else{
            JOptionPane.showMessageDialog(null, "No hay ningún préstamo preconcedido","Cálculo de los Préstamos preconcedidos",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBCalculoActionPerformed

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        // TODO add your handling code here:
        jPPortada.setVisible(true);
        jPSolicitar.setVisible(false);
        jPCalcularPrestamo.setVisible(false);
        jPMostrar.setVisible(false);

    }//GEN-LAST:event_jBVolverActionPerformed

    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
        // TODO add your handling code here:
        jPPortada.setVisible(false);
        jPSolicitar.setVisible(false);
        jPCalcularPrestamo.setVisible(true);
        jPMostrar.setVisible(false);
    }//GEN-LAST:event_jBCalcularActionPerformed

    private void jTIntroDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIntroDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIntroDNIActionPerformed

    private void jBPLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPLimpiarActionPerformed
        // TODO add your handling code here:
        jTextFieldDatoMostrar.setText("");
    }//GEN-LAST:event_jBPLimpiarActionPerformed

    private void jBFirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFirmarActionPerformed

    private void jScrollPaneConcedidosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jScrollPaneConcedidosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPaneConcedidosAncestorAdded

    private void jBPreconcedidos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPreconcedidos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBPreconcedidos2ActionPerformed

    private void jBVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolver1ActionPerformed
        // TODO add your handling code here:
        jPPortada.setVisible(true);
        jPSolicitar.setVisible(false);
        jPCalcularPrestamo.setVisible(false);
        jPMostrar.setVisible(false);
        jPFirmar.setVisible(false);

    }//GEN-LAST:event_jBVolver1ActionPerformed

    private void jBBFirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBFirmarActionPerformed
        // TODO add your handling code here:
        jPPortada.setVisible(false);
        jPSolicitar.setVisible(false);
        jPCalcularPrestamo.setVisible(false);
        jPMostrar.setVisible(false);
        jPFirmar.setVisible(true);
    }//GEN-LAST:event_jBBFirmarActionPerformed

    private void jButtonProcesarSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcesarSolicitarActionPerformed
        // TODO add your handling code here:

        String dni = jTextFieldDNISolicitar.getText();

        if (dni == null || dni.equals("")) {
            JOptionPane.showMessageDialog(null, "DNI vacío.", "Informativo", JOptionPane.INFORMATION_MESSAGE, null);
        } else {

            Cliente clienteApto = Funciones.aptoParaPrestamo(MetodosBD.clientePorDni(dni));

            if (clienteApto != null) {
                System.out.println("Apto para préstamo");
                System.out.println("Cantidad: " + Funciones.cantidadPrestamo(clienteApto));
                JOptionPane.showMessageDialog(null, "Apto para préstamo. Cantidad = " + Funciones.cantidadPrestamo(clienteApto), "Informativo", JOptionPane.INFORMATION_MESSAGE, null);
                MetodosBD.insertarPrestamopreconcedido(new PrestamoPreconcedido(15, 2, 24, clienteApto, LocalDate.now(), Funciones.cantidadPrestamo(clienteApto)));
            } else {
                System.out.println("No apto para préstamo.");
            }
        }

    }//GEN-LAST:event_jButtonProcesarSolicitarActionPerformed

    private void jScrollPanePrestamoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jScrollPanePrestamoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPanePrestamoAncestorAdded

    private void jButtonBuscarMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarMostrarActionPerformed
        // TODO add your handling code here:

//        Cliente cliente = MetodosBD.clientePorDni("32109876J");
//        PrestamoPreconcedido prestamoPre = MetodosBD.prestamoPrePorIdCliente(cliente.getUuid());
//        //System.out.println(MetodosBD.prestamoPrePorIdCliente(cliente.getUuid()).toString());
//
//        String[] columnasTablaSolicitar = {"DNI", "Nombre", "Apellidos", "Cantidad", "Fecha oferta"};
//        String[] datosCliente = {cliente.getDni(), cliente.getNombre(), cliente.getApellidos(), String.valueOf(prestamoPre.getCantidad()), prestamoPre.getFecha().toString()};
//        DefaultTableModel modeloTabla = new DefaultTableModel(null, columnasTablaSolicitar);
//        jTableMostrar.setModel(modeloTabla);
//        modeloTabla.addRow(datosCliente);
        List<Cliente> clientes = MetodosBD.listarClientes();
        String[] columnasTablaSolicitar = {"DNI", "Nombre", "Apellidos"};
        DefaultTableModel modeloTabla = new DefaultTableModel(null, columnasTablaSolicitar);
        jTableMostrar.setModel(modeloTabla);

        for (Cliente cliente : clientes) {
            String[] datosCliente = {cliente.getDni(), cliente.getNombre(), cliente.getApellidos()};
            modeloTabla.addRow(datosCliente);
        }

    }//GEN-LAST:event_jButtonBuscarMostrarActionPerformed
/**
 * 
 * @param evt 
 */
    private void jGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGrabarActionPerformed
        // TODO add your handling code here:
        File fichero=new File("PrestamosPreconcedidos.txt");
        List<PrestamoPreconcedido>lista=MetodosBD.listarPrestamosPreconcedidos();
        if(!fichero.exists()){
            Ficheros.escribirLineaALineaDeListPrestamosPreconcedidos(fichero, lista);
            JOptionPane.showMessageDialog(null, "Se ha grabado en un fichero correctamente","Fichero Preconcedidos",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jGrabarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DNI;
    private javax.swing.JButton jBBFirmar;
    private javax.swing.JButton jBCalcular;
    private javax.swing.JButton jBCalculo;
    private javax.swing.JButton jBFirmar;
    private javax.swing.JButton jBMostrar;
    private javax.swing.JButton jBPLimpiar;
    private javax.swing.JButton jBPreconcedidos2;
    private javax.swing.JButton jBSolicitar;
    private javax.swing.JButton jBVolver;
    private javax.swing.JButton jBVolver1;
    private javax.swing.JButton jBVolverMostrar;
    private javax.swing.JButton jButtonBuscarMostrar;
    private javax.swing.JButton jButtonBuscarSolicitar;
    private javax.swing.JButton jButtonLimpiarMostrar;
    private javax.swing.JButton jButtonLimpiarSolicitar;
    private javax.swing.JButton jButtonProcesarSolicitar;
    private javax.swing.JButton jButtonVolverSolicitar;
    private javax.swing.JComboBox<String> jComboBoxFiltroMostrar;
    private javax.swing.JButton jGrabar;
    private javax.swing.JLabel jLCalculoPrestamo;
    private javax.swing.JLabel jLFirmarPrestamo1;
    private javax.swing.JLabel jLPrestamoConcedido;
    private javax.swing.JLabel jLPrestamoPreconcedido1;
    private javax.swing.JLabel jLabelDNISolicitar;
    private javax.swing.JLabel jLabelDatosClienteSolicitar;
    private javax.swing.JLabel jLabelFiltroMostrar;
    private javax.swing.JLabel jLabelMostrar;
    private javax.swing.JLabel jLabelTituloSolicitar;
    private javax.swing.JPanel jPCalcularPrestamo;
    private javax.swing.JPanel jPFirmar;
    private javax.swing.JPanel jPMostrar;
    private javax.swing.JPanel jPPortada;
    private javax.swing.JPanel jPSolicitar;
    private javax.swing.JScrollPane jScrollPane1Mostrar;
    private javax.swing.JScrollPane jScrollPaneClientesSolicitar;
    private javax.swing.JScrollPane jScrollPaneConcedidos;
    private javax.swing.JScrollPane jScrollPanePreconcedido;
    private javax.swing.JScrollPane jScrollPanePrestamo;
    private javax.swing.JTextField jTIntroDNI;
    private javax.swing.JTable jTableCalculo;
    private javax.swing.JTable jTableMostrar;
    private javax.swing.JTable jTableSolicitar;
    private javax.swing.JTextField jTextFieldDNISolicitar;
    private javax.swing.JTextField jTextFieldDatoMostrar;
    private javax.swing.JLabel lblFondoFirmar;
    private javax.swing.JLabel lblFondoMostrar;
    private javax.swing.JLabel lblFondoSolicitar;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
